project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        reverting_tx_gas_limit: false
        default_contract_owner: false


compiler:
    evm_version: null
    vyper:
        version: 0.2.12